name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: rm -rf dist && pnpm run pre-release && pnpm run semantic-release
      - name: Bump package version
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            CHANGELOG.md
            package.json
          commit-message: "chore(release): bump version and update CHANGELOG.md [skip ci]"
          committer: "release-bot <noreply@github.com>"
          branch: release
          delete-branch: true
          title: "chore(release): bump version and update CHANGELOG.md [skip ci]"
          body: "This PR bumps the version in `package.json` and updates `docs/CHANGELOG.md`."
